### ISSUE TITLE
Integrate results with stats from rankings

### ISSUE THREAD

**Issue by EndBug** [PoliNetworkOrg/TheTOLProject#16]
Proposal author: [@spyarect](https://t.me/spyarect)

PoliNetwork keeps a log of TOL rankings at [rankings.polinetwork.org](https://rankings.polinetwork.org/). We could use this data to give the user some info on how they would have ranked in previous years, and in different degree courses.

**Comment by zagbc** [comment]
We could run an independent data visualization and stats project based on all available ranking datasets, I mean not just Engineering.

It could be an opportunity to start an inclusive & diverse project at PoliMi in order to enrich our technical community. Perhaps, it could be linked to GitHub education programs. If you agree and available, it would be my pleasure to manage it or just collaborate to get the job done. Starting from 2023.

**Comment by zagbc** [comment]
Closed via rankings.polinetwork.org (web app)
